___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
# print(np.__version__)
# np.show_config()

Створити вектор з 10 елементів, заповнений одиницями:

In [43]:
arr=np.ones((1, 10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Створити вектор із значеннями від 0 до 10:

In [44]:
arr=np.arange(0, 11, 1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [45]:
arr=np.full((5, 5), 0)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [62]:
arr=np.random.randint(1, 20, (1, 20))
arr

array([[ 6,  7,  3, 16, 16,  3, 14,  1, 12, 17,  9, 19, 13, 10,  2,  4,
         7,  4,  2, 14]])

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [82]:
print(np.mean(arr))
print(np.median(arr))
print(round(np.std(arr), 2))

8.95
8.0
5.65


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [103]:
arr1=np.random.randint(1, 10, (4, 2))
arr2=np.random.randint(1, 10, (2, 2))

arr_m=arr1.dot(arr2)#matmul()
# print(arr1)
# print(arr2)
# print(arr_m)

[[2 1]
 [5 3]
 [8 5]
 [6 6]]
[[2 5]
 [8 3]]
[[12 13]
 [34 34]
 [56 55]
 [60 48]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [131]:
#arr_v=arr_m.reshape(1,8)
#print(arr_v)

arr_v[max(np.argmax(arr_v, axis=0))][np.argmax(arr_v, axis=1)]=0
#print(arr_v)

[[12 13 34 34 56 55 60 48]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

Дано матрицю. Знайти ранг матриці:

In [135]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [136]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [141]:
eigenvalues, eiegnvectors = np.linalg.eig(a)

print(eigenvalues)
print()
print(eiegnvectors)

[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]

[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [201]:
a = np.random.randint(0,10,50)
a

array([4, 7, 8, 6, 8, 5, 0, 3, 6, 7, 2, 5, 6, 1, 4, 2, 6, 3, 3, 7, 1, 1,
       3, 1, 7, 2, 3, 1, 5, 2, 7, 1, 4, 3, 3, 7, 5, 2, 8, 7, 6, 6, 3, 1,
       4, 0, 9, 6, 4, 3])

In [217]:
unique, counts = np.unique(a, return_counts=True)
d=dict(zip(unique, counts))
[{k:v} for k, v in d.items() if v==max(d.values())]

[{9: 8}]

Виведіть лише парні числа, що діляться на 5:

In [203]:
a = np.random.randint(0,10,50)
a

array([0, 7, 5, 2, 5, 6, 9, 5, 9, 6, 4, 6, 0, 2, 3, 8, 9, 1, 2, 3, 1, 8,
       6, 0, 5, 0, 9, 8, 2, 3, 1, 5, 3, 9, 1, 7, 5, 2, 7, 0, 4, 9, 8, 5,
       3, 8, 9, 6, 9, 8])

In [225]:
[i for i in list(a) if i%5==0 if i%2==0]

[0, 0, 0, 0, 0]

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [227]:
arr=np.array([[2, 5], [1, -10]])
v=np.array([1, 3])
np.linalg.solve(arr, v)

array([ 1. , -0.2])